"use client";

import * as React from "react";
import { applyActionCode, confirmPasswordReset, verifyPasswordResetCode } from "@firebase/auth";
import Link from "next/link";
import { auth } from "@/lib/firebase";

type Phase = "checking" | "form" | "done" | "error";

export default function AuthActionPage() {
  const [phase, setPhase] = React.useState<Phase>("checking");
  const [mode, setMode] = React.useState("");
  const [code, setCode] = React.useState("");
  const [email, setEmail] = React.useState("");
  const [password, setPassword] = React.useState("");
  const [confirm, setConfirm] = React.useState("");
  const [error, setError] = React.useState("");
  const [busy, setBusy] = React.useState(false);

  React.useEffect(() => {
    // Firebase redirects here with ?mode=<action>&oobCode=<generated code>&continueUrl=...
    // The mode and oobCode are generated by Firebase — this page only validates and applies them.
    const params = new URLSearchParams(window.location.search);
    const actionMode = params.get("mode") || "";
    const oobCode = params.get("oobCode") || "";
    setMode(actionMode);
    setCode(oobCode);

    if (actionMode === "resetPassword" && oobCode) {
      verifyPasswordResetCode(auth, oobCode)
        .then((verifiedEmail) => {
          setEmail(verifiedEmail);
          setPhase("form");
        })
        .catch(() => {
          setError("This password reset link is invalid or has expired. Please request a new one.");
          setPhase("error");
        });
      return;
    }

    if ((actionMode === "verifyEmail" || actionMode === "recoverEmail") && oobCode) {
      applyActionCode(auth, oobCode)
        .then(() => setPhase("done"))
        .catch(() => {
          setError("This verification link is invalid or has expired. Please log in and request a new one.");
          setPhase("error");
        });
      return;
    }

    setError("This link is not valid. Please request a new email.");
    setPhase("error");
  }, []);

  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setError("");
    if (password.length < 6) {
      setError("Password should be at least 6 characters.");
      return;
    }
    if (password !== confirm) {
      setError("Passwords do not match.");
      return;
    }
    setBusy(true);
    try {
      await confirmPasswordReset(auth, code, password);
      setPhase("done");
    } catch {
      setError("Could not update the password. The link may have expired — please request a new reset email.");
    } finally {
      setBusy(false);
    }
  }

  const title = mode === "resetPassword" ? "Set a new password" : "Account verification";

  return (
    <main className="grid min-h-dvh place-items-center bg-[#f6f6f4] px-4 text-[#1f1f1f]">
      <section className="w-full max-w-sm rounded-xl border border-[#e4e7ec] bg-white p-6 shadow-sm">
        {phase === "checking" ? (
          <p className="text-center text-sm text-neutral-500">Checking link…</p>
        ) : null}

        {phase === "form" ? (
          <form onSubmit={submit}>
            <h1 className="text-base font-semibold tracking-tight">{title}</h1>
            <p className="mt-1 text-xs text-neutral-500">Setting a new password for {email}</p>
            <div className="mt-5 grid gap-4">
              <label className="block text-xs font-medium text-neutral-600">
                New password
                <input
                  value={password}
                  onChange={(event) => setPassword(event.target.value)}
                  type="password"
                  autoComplete="new-password"
                  required
                  className="mt-1.5 h-10 w-full rounded-md border border-neutral-200 bg-white px-3 text-sm text-neutral-900 outline-none transition focus:border-neutral-400 focus:ring-2 focus:ring-neutral-100"
                />
              </label>
              <label className="block text-xs font-medium text-neutral-600">
                Confirm new password
                <input
                  value={confirm}
                  onChange={(event) => setConfirm(event.target.value)}
                  type="password"
                  autoComplete="new-password"
                  required
                  className="mt-1.5 h-10 w-full rounded-md border border-neutral-200 bg-white px-3 text-sm text-neutral-900 outline-none transition focus:border-neutral-400 focus:ring-2 focus:ring-neutral-100"
                />
              </label>
            </div>
            {error ? <p className="mt-3 text-sm font-medium text-red-600">{error}</p> : null}
            <button
              disabled={busy}
              className="mt-5 h-10 w-full rounded-md bg-neutral-900 text-sm font-medium text-white transition hover:bg-neutral-700 disabled:cursor-not-allowed disabled:opacity-60"
              type="submit"
            >
              {busy ? "Updating…" : "Update password"}
            </button>
          </form>
        ) : null}

        {phase === "done" ? (
          <div className="text-center">
            <h1 className="text-base font-semibold tracking-tight">
              {mode === "resetPassword" ? "Password updated" : "Email verified"}
            </h1>
            <p className="mt-2 text-sm text-neutral-500">
              {mode === "resetPassword"
                ? "Your password has been changed. You can now log in with your new password."
                : "Your email has been verified. You can now log in."}
            </p>
            <Link
              href="/login"
              className="mt-5 inline-flex h-10 items-center rounded-md bg-neutral-900 px-5 text-sm font-medium text-white transition hover:bg-neutral-700"
            >
              Go to log in
            </Link>
          </div>
        ) : null}

        {phase === "error" ? (
          <div className="text-center">
            <h1 className="text-base font-semibold tracking-tight">Link problem</h1>
            <p className="mt-2 text-sm text-red-600">{error}</p>
            <Link
              href="/login"
              className="mt-5 inline-flex h-10 items-center rounded-md border border-neutral-200 px-5 text-sm font-medium text-neutral-700 transition hover:bg-neutral-50"
            >
              Back to log in
            </Link>
          </div>
        ) : null}
      </section>
    </main>
  );
}